site_name: ontoink Demo
theme: readthedocs
nav:
  - Home: index.md
  - Examples:
    - FOAF Person: examples/foaf-person.md
    - Schema.org Article: examples/schema-article.md

plugins:
  - search
  - ontoink

markdown_extensions:
  - pymdownx.superfences:
      preserve_tabs: true
